### PR TITLE
Category Page

### PR DESCRIPTION
**Pull request by brenoc**

### CODE REVIEW

**Comment by brenoc** [comment]
@dfosco @tamorim this MUST be rebased. Don't wait until this code is ready, do it everyday.

**Comment by tamorim** [comment]
I always rebase, I didnt saw master get updated...

**Comment by tamorim** [comment]
The correct branch is feature/categoryPage, that is why it's not rebased

**Comment by dfosco** [comment]
Well, I guess this branch _could_ be constantly rebased as well, but it's meant to be a quick & dirty prototype branch — rebasing constantly is more important in the `feature` version.

**Comment by tamorim** [comment]
I really think that this should be closed, it's not this branch that will be merged.

**Pull request closed without merging**
