### PR TITLE
Use app vtex.product-page

### PR DESCRIPTION
**Pull request by brenoc**

### CODE REVIEW

**Comment by brenoc** [comment]
@tamorim can you review this it and https://github.com/vtex-apps/product-page please?

The `assign` action will be killed with the areas feature.

**Comment by tamorim** [comment]
@brenoc Really interesting! Loved what you've done :D 
I think that the documentation must make clear that it's only a utility, not a MUST use.
It's good for the sense of freedom, you know? And he can always base himself on the wrapper if he wants to go nuts, I guess...

**Comment by brenoc** [comment]
@tamorim sure, maybe you can open an issue on the other repo about that

**Comment by tamorim** [comment]
:+1:

**Pull request merged**
