### PR TITLE
Improve assets loaded on the page

### PR DESCRIPTION
**Pull request by amoreira**
these are small changes to improve the size of the assets loaded on the page. =)

### CODE REVIEW

**Comment by tamorim** [comment]
@amoreira You've missed the `ExplorerButton` component, he uses SVGIcon too.

**Comment by tamorim** [comment]
@amoreira Oh, and add the desktop menu is completely unrelated to the PR.
It should be done somewhere else... It envolves some tweaking too, because it looks completely horrible just laid out like this.

**Comment by amoreira** [comment]
@tamorim done!

**Comment by tamorim** [comment]
LGTM :money_with_wings:

**Pull request merged**
