### PR TITLE
[Review] Responsive Category Page

### PR DESCRIPTION
**Pull request by dfosco**
**Category Header**
 - [x] Responsive layout
 - [x] Improve grid button style 
 - [x] Change grid button text between `grid` and `list`

---

**Product List**
 - [x] Close Product List pull request ([#5](https://github.com/vtex-apps/product-list/pull/5))

---

**Category List**

 - [x] Category List
 - [x] Category List (functional)

---

**Filters and Ordenation**

 - [x] Filters Sidebar
 - [x] Filters Sidebar (functional)
 - [x] Ordenation selector
 - [x] Ordenation selector (functional)

---

**Filter Panel**
 - [x] Close Filter Panel pull request ([#11](https://github.com/vtex-apps/filter-panel/pull/11))

### CODE REVIEW

**Comment by dfosco** [comment]
@tamorim Views are done, now we need to use resource binding to make the desktop filters functional

**Comment by dfosco** [comment]
@tamorim To be honest, I think all categories, filters — both desktop and mobile views — should go into `filter-panel` app, that should actually be called `product-filters`

**Comment by dfosco** [comment]
@tamorim To be honest, I think all categories, filters, brands and ordenation (both desktop and mobile views) should go into `filter-panel` app, that should actually be called `product-filters`.

Ideally, this app could be called anywhere a list of products is displayed (maybe the `product-list` app itself) and affect its behavior

**Comment by tamorim** [comment]
@dfosco I've made everything functional! The only thing that it lacks now it's the styling for the Filters. I've made some changes to override some stuff, but it lacks the final touch :smile: 

Can you do that?
Also, see if you catch any bugs!

**Comment by dfosco** [comment]
@tamorim Awesome! Will tackle it later today so we can close it asap :smile:

**Comment by dfosco** [comment]
@tamorim Review pls and _I think we're done here_ 🎉

**Comment by dfosco** [comment]
@tamorim WAIT. One more style to adjust :sweat_smile:

**Comment by dfosco** [comment]
@tamorim Cool, now we're done!

**Pull request merged**
