### PR TITLE
Use search-bar app

### PR DESCRIPTION
**Pull request by brenoc**
Add https://github.com/vtex-apps/search-bar to theme

### CODE REVIEW

**Comment by tamorim** [comment]
@brenoc Isn't a little weird to pass the SearchBar to the Header component on every page?
The page is getting an asset that it doesn't need, just to pass to Header... seems a little strange.

**Comment by brenoc** [comment]
@tamorim yeah, maybe Header should just listen to the ComponentStore and do this job instead. We'll need to rethink that after the Great Break™

**Comment by dfosco** [comment]
@tamorim @brenoc What's pending here — is it using search-bar as a standalone installed app? Your conversation went a bit over my head :joy:

**Comment by tamorim** [comment]
:zap:

**Pull request merged**
